### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by MatthewKhouzam** [argonne-lcf/THAPI#168]
In the readme: 
`For complain, praise, or bug reports please use: <(o )___`

in `xprof.sh.erb.in`: 
`echo "For complaints, praises, or bug reports please use: <(o )___"`

This seems to be a copy-paste issue.

**Comment by TApplencourt** [comment]
Thanks! Good call. 

I will update the README on https://github.com/argonne-lcf/THAPI/pull/162 (which is a significant rewrite of the `iprof` binary).

A lot of work is needed in the documentation in general... So thanks to help improving it a little bit already :)
