### ISSUE TITLE
Help for max size 

### ISSUE THREAD

**Issue by TApplencourt** [argonne-lcf/THAPI#7]
Reported by Marta:

>--max-name-size  Maximun size allowed for names
> so I assumed there was a default size by default and a max. size set while activating that.
> Maybe it would be good to add something like this (btw, there is a typo in the last letter of maximummmmm:
> --max-name-size  Maximun size allowed for names (default XXX characters), e.g. --max-nam-size 1000

**Comment by martagarciamartinez** [comment]
As of know, XXX = 100 characters

**Comment by TApplencourt** [comment]
Fixed by `e17c9b4`
