### ISSUE TITLE
Build experience on Ubuntu 22.04

### ISSUE THREAD

**Issue by markdewing** [argonne-lcf/THAPI#70]
I built on Ubuntu 22.04.02
* protoc is not listed as a dependency ("protobuf-compiler" package on Ubuntu)
* babeltrace2 version is 2.0.4.  It appears that version does not have the mentioned patch.  However, I could not get babeltrace2 to configure (autoconf errors), so I went with the system version (2.0.4).  I'm not sure what sort of errors the unpatched version might cause?
* Had a error on "failure on PKG_CHECK_MODULES syntax error near unexpected token".  Fix was to install/update "pkg-config" package.
* After installing ruby, command to install ruby gems on Ubuntu: "sudo gem install <pkgname>"

**Comment by TApplencourt** [comment]
We recommend to use `spack` to install iprof as for the patch.


>babeltrace2 version is 2.0.4. It appears that version does not have the mentioned patch. However, I could not get babeltrace2 to configure (autoconf errors), so I went with the system version (2.0.4). I'm not sure what sort of errors the unpatched version might cause?

I think segfault :) . I will let Brice response on this topic and others with more in-depth responses when he is back from his well-deserved vacation.

**Comment by Kerilk** [comment]
Yes, this will cause binary values (structures and kernel arguments to be incompletely read from the trace) and in the worst case to segfaults.

The list of dependencies is a bit long, did you try using `sudo apt build-dep babeltrace2` to install the required dependencies? This should solve most of your issues.

I build it on 22.04 and have nothing on the configure line except the prefix I want to install it to.
