### ISSUE TITLE
Name mangling option not working

### ISSUE THREAD

**Issue by DonAurelio** [argonne-lcf/THAPI#89]
```bash
iprof: a tracer / summarizer of OpenCL, L0, CUDA, HIP, and OMPT driver calls
Usage
...
  --mangle                  Use mangled name
...
```

```  bash
iprof --mangle ./a.out 
Trace location: /home/avivasmeza/lttng-traces/iprof-20230613-213803
Traceback (most recent call last):
/soft/debuggers/thapi/0.12.0/bin/babeltrace_thapi:92:in `<main>': invalid option: --mangling=mangle (OptionParser::InvalidOption)
```

Seems there is a mismatch between the argument name expected (`name`) and the one we pass (`mangling`). But I still need to understand how this argument passing works.

https://github.com/argonne-lcf/THAPI/blob/9a96ead21c1b25145f24e6f955d9a85acc4726be/xprof/xprof.sh.erb.in#L386

https://github.com/argonne-lcf/THAPI/blob/9a96ead21c1b25145f24e6f955d9a85acc4726be/utils/babeltrace_thapi.in#L23

**Comment by TApplencourt** [comment]
Can reproduce

**Comment by TApplencourt** [comment]
We need to pass `name=mangle` and not `--mangle` when calling `babeltrace_thapi`

**Comment by TApplencourt** [comment]
`        --mangle)               shift; bt_tally_argv+=" --mangling=mangle" ;;` should be `        --mangle)               shift; bt_tally_argv+=" --name=mangle" ;;`
