### ISSUE TITLE
iprof stop working after using --no-save

### ISSUE THREAD

**Issue by DonAurelio** [argonne-lcf/THAPI#91]
When I issued this command, iprof works properly by displaying the tally.

```bash
.../thapi/build/ici/bin/iprof ./a.out
```

Then I used the `--no-save` option: (1) it does print the result, (2) it makes iprof to no work after 

```bash
.../thapi/build/ici/bin/iprof ./a.out
```
Finally, when trying to use iprof again, it doesn't work, i.e., it doesn't display the tally.

```bash
.../thapi/build/ici/bin/iprof ./a.out
```

**Comment by TApplencourt** [comment]
Yeah, that mean something wrong append you need to use the `--clean-up`. `--no-save` is sometime broken we know about it.  :(

**Comment by TApplencourt** [comment]
Fix it was sue to some reusing of file not cleaned-up
