### ISSUE TITLE
@Kerilk and @TApplencourt, I am getting this error in the CI, but i do not see how it is related to my PR, any clue?

### ISSUE THREAD

**Issue by TApplencourt** [argonne-lcf/THAPI#95]
@Kerilk and @TApplencourt, I am getting this error in the CI, but i do not see how it is related to my PR, any clue?

```bash 
/home/runner/work/THAPI/THAPI/opencl/opencl_model.rb:41:in `initialize': No such file or directory @ rb_sysopen - cl.xml.patched (Errno::ENOENT)
```

_Originally posted by @DonAurelio in https://github.com/argonne-lcf/THAPI/issues/93#issuecomment-1603431292_

**Comment by TApplencourt** [comment]
Maybe a race condition in our build-sytem

**Comment by Kerilk** [comment]
Yeah, I fixed it there: https://github.com/argonne-lcf/THAPI/pull/96
